name: Hormones
version: 2.0.0
api:
- 3.0.0-alpha5
main: Hormones\HormonesPlugin
authors:
- SOFe
softdepend:
- SimpleAuth
- ServerAuth
- HereAuth
- PiggyAuth

permissions:
  hormones:
    default: false
    description: Allows full access to Hormones. A very powerful permission.
    children:
      hormones.transfer:
        description: Allows transferring to other tissues
        default: op
        children:
          hormones.transfer.organic:
            description: Allows transferring to a specific organ
            default: op
#          hormones.transfer.specific:
#            description: Allow transferring to a specific tissue
#            default: true
      hormones.admin:
        description: Allows administrative access to the network, i.e. those related to server maintenance.
        default: false
        children:
          hormones.admin.stop:
            description: Allows triggering shutdown/restart of all network servers.
            default: false
      hormones.moderation:
        default: false
        children:
          hormones.moderation.moderator:
            default: false
            children:
              hormones.moderation.moderator.sectional:
                default: op
                children:
                  hormones.moderation.moderator.sectional.ban:
                    default: op
                  hormones.moderation.moderator.sectional.mute:
                    default: op
                  hormones.moderation.moderator.sectional.broadcast:
                    default: op
              hormones.moderation.moderator.global:
                default: false
                children:
                  hormones.moderation.moderator.global.ban:
                    default: false
                  hormones.moderation.moderator.global.mute:
                    default: false
                  hormones.moderation.moderator.global.broadcast:
                    default: false
