---
name: Hormones
version: 1.0.0-build0000
api: [2.0.0]
main: Hormones\HormonesPlugin
description: An advanced plugin designed for networks with multiple servers
softdepend: [SimpleAuth]
author: LegendsOfMCPE Team
authors: [PEMapModder]
...
