--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LegendOfMCPE/Hormones
projects:
  Hormones:
    path: Hormones/
    stub: stubs/entry.php
    includeDirs:
      stubs: =
    includeFiles:
      /phagocyte.php: stubs/phagocyte.php
    libs:
      - src: poggit/libasynql/libasynql
        version: 1.1.0
...
