--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LegendOfMCPE/Hormones
projects:
  Hormones:
    path: Hormones/
    stub: phagocyte.php
    libs:
      - src: poggit/libasynql/libasynql
        version: 1.1.0
...
