---
Dear User: Please delete this line after you have finished setting up the config file.

# MySQL database setup
# You must use the same database and schema for all your plugins.
# The user used for hormones should have access to LOCK, CREATE, SELECT, INSERT, UPDATE and DELETE all tables in the schema.
mysql:
  host: 127.0.0.1
  username: root
  password: ""
  schema: hormones
  port: 3306
  socket: ""

# Localized information for this server
localize:
  organ: normal # The type name of the server. Can be anything you want. Players may be transferred to other servers of the same oragn if server full. Case-insensitive.
  name: auto # set a unique name for this server, merely for displaying to you. Writing "auto" will be replaced by the server IP + port.
  address: auto # replace this with a DNS address that points to this server. Otherwise this will be replaced by an automatically detected external IP.
                # "address: auto" may not work if an IPv6 address is reported by online services.

# The kidney cleans old hormones.
# Since hormones are only used as a temporary medium of communication among servers in your network,
# the kidney should be operated regularly to prevent the database from storing a large amount of unneeded data.
# You may only want to disable the kidney for debug purposes.
# You might only need to enable kidney in any one of the servers in your network, but it doesn't hurt to enable in all.
# Enabling the kidney on all servers should not have notable negative impact on server performance.
kidney:
  enabled: true # whether to enable the kidney.
  interval: 600 # frequency to delete old hormones, in seconds
  expiry: 300 # number of seconds that hormones should stay in blood before being deleted

balancer:
  # This will only prevent transferring players to other tissues. Other tissues of the same organ ID may still transfer players to this tissue.
  enabled: true
  # Normal number of slots. Special players can bypass this limit but are still limited by the max-players in server.properties
  # If the soft limit is reached, normal players will be transferred to another server with the most empty slots.
  playerSoftLimit: 18
  # List of players (usernames, case-insensitive) who can bypass the soft limit.
  exemptPlayers:
  - shogchips

# Ensures that no two logged-in players on the network will have the same name at the same moment
singleSession:
  # Action to do if there is collision. Possible values:
  #     off: Disable singleSession
  #     bump: Disallow login if a player of such name is already logged in in the network (in any organs, any tissues)
  #     push: Kick any other players if the condition in singleSession.pushUpon is met
  #     ip-push: push if both players have the same IP, bump if different IP

  # IMPORTANT: Make sure you use the same setttings on all network servers.
  mode: off

  # The auth plugin integration to use
  # This will be used to detect whether a player is online and logged in.
  # Possible values: none, SimpleAuth, ServerAuth, HereAuth, PiggyAuth
  # If "none" is chosen, player is considered "logged in" as long as the player is connected and remains online (even before being spawned)
  authIntegration: none
...
