---
name: HormonesUtils
version: 1.0.0-SNAPSHOT
api: [2.0.0]
main: Hormones\HormonesUtils\HormonesUtils
description: General network management plugin based on Hormones
depend: [Hormones]
softdepend: []
author: LegendsOfMCPE Team
authors: [PEMapModder]
...
